apiVersion: v1
kind: Service
metadata:
  name: load-aware-scheduler-dashboard
  namespace: load-aware-scheduler
  labels:
    app.kubernetes.io/name: load-aware-scheduler
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: load-aware-scheduler
  ports:
    - name: http
      port: 8080
      targetPort: http
